name: Distribution

on:
  workflow_dispatch:
  
jobs:

  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build artifact
      run: .github/workflows/build.sh
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: dcraw-windows.zip